# RlLight plugin by gasnic
# Support: https://discord.gg/JJayWyCzBV
# Versions: 1.8-1.20
# support by Olomowo Studio (2024)

messages:
  playeronly: "this command cannot be used as console."
  nopermission: "you do not have permission to use this command."
  maxradius: "You must change the radius in config!"
  reload: "reloaded config."
  usage: "To use /rlight, you must provide an argument (int)."
# here you can set your own message names
permissions:
  start: "rlight.start"
  reload: "rlight.reload"

# here you can set your own permission names
maxRadius: 100
# maxRadius is the maximum range at which the plugin will place light blocks
